//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLandScape.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class en_EN : global::System.Configuration.ApplicationSettingsBase {
        
        private static en_EN defaultInstance = ((en_EN)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new en_EN())));
        
        public static en_EN Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Object")]
        public string menuStripObject {
            get {
                return ((string)(this["menuStripObject"]));
            }
            set {
                this["menuStripObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tools")]
        public string menuStripTools {
            get {
                return ((string)(this["menuStripTools"]));
            }
            set {
                this["menuStripTools"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Finance")]
        public string menuStripFinance {
            get {
                return ((string)(this["menuStripFinance"]));
            }
            set {
                this["menuStripFinance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Help")]
        public string menuStripHelp {
            get {
                return ((string)(this["menuStripHelp"]));
            }
            set {
                this["menuStripHelp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Projects generator")]
        public string menuStripGenerator {
            get {
                return ((string)(this["menuStripGenerator"]));
            }
            set {
                this["menuStripGenerator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Version 0.1 is live! Check README.md")]
        public string listBoxNews {
            get {
                return ((string)(this["listBoxNews"]));
            }
            set {
                this["listBoxNews"] = value;
            }
        }
    }
}
